urls.py
from django.urls import path, include
from . import views

urlpatterns = [
]

models.py
from django.db import models
from geriatrics.models import Admission
from medication.models import Medication

# Create your models here.
class Kardex(models.Model):
    resident = models.OneToOneField(Admission, on_delete=models.CASCADE) 
    known_allergies = models.CharField(max_length=250, blank=True)
    vital_signs_monitoring = models.CharField(max_length=250, blank=True) 
    # Precaution
    fall = models.BooleanField() 
    pressure_ulcer = models.BooleanField() 
    bleeding = models.BooleanField() 
    aspiration = models.BooleanField() 
    infection = models.BooleanField() 
    wandering = models.BooleanField() 
    others = models.BooleanField() 
    specify = models.CharField(max_length=250, blank=True) 

    def __str__(self):
        return f'{self.resident}'

    class Meta:
        verbose_name_plural = 'Kardexes'
        
class OrganSystem(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
        
class Diagnosis(models.Model):
    kardex = models.ForeignKey(Kardex, on_delete=models.CASCADE, null=True)
    system = models.ForeignKey(OrganSystem, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now=False, null=True, blank=True)
    diagnosis = models.CharField(max_length=250, db_index=True)

    def __str__(self):
        return f'{self.name}' 

    class Meta:
        ordering = ['system']
        verbose_name_plural = 'Diagnoses'
        
    def __str__(self):
        return f'{self.kardex}: {self.date}-{self.diagnosis}'
       
class PrescribedMedication(models.Model):
    diagnosis = models.ForeignKey(Diagnosis, on_delete=models.CASCADE)
    medication = models.ForeignKey(Medication, on_delete=models.CASCADE)	

    def __str__(self):
        return f'{self.diagnosis}/{self.medication}'

class Therapy(models.Model):
    resident = models.ForeignKey(Admission, on_delete=models.CASCADE, limit_choices_to={'discharged': False})
    therapy = models.CharField(max_length=120) 
    schedule = models.TextField()

    def __str__(self):
        return f'{self.resident}: {self.therapy}'

    class Meta:
        verbose_name_plural = 'Therapies'

views.py
from django.shortcuts import render

# Create your views here.

templates/kardex/includes/kardex.html
{% with kardex=resident.kardex %}
<div class="table-responsive-sm">
  <table class="table table-sm table-hover">
    <tr>
      <td><strong>Name:</strong> {{ resident }}</td>
      <td><strong>Age:</strong> {{ resident.date_of_birth|timesince }}</td>
      <td><strong>Date of Birth:</strong> {{ resident.date_of_birth }}</td>
      <td><strong>Room No.:</strong> {{ resident.room }}</td>          
    </tr>
    <tr>
      <td rowspan="2" colspan="2"><strong>Attending Physician:</strong></td> 
      <td><strong>Admission date:</strong> {{ admission.date_of_admission }}</td>      
      <td><strong>Height:</strong> {{ resident.height_in_cm }}</td>       
    </tr>     
    <tr>      
      <td><strong>Admitted by:</strong> {{ admission.admitted_by }}</td>
      <td><strong>Weight:</strong> {{ resident.weight_in_kg }}</td>
    </tr>
    <tr>
      <td><strong>Date:</strong></td>
      <td><strong>Diagnosis:</strong></td>    
    </tr>
    {% for diagnosis in resident.diagnosis_set.all %}
    <tr>
      <td>{{ diagnosis.date }}</td>
      <td>{{ diagnosis.diagnosis }}</td>
    </tr>
    {% endfor %}      
    <tr>
      <td colspan="2"><strong>Diet:</strong> {{ resident.diet }}</td>        
    </tr>
    <tr>
      <td colspan="2"><strong>Known Allergies:</strong> {{ kardex.known_allergies }}</td>      
    </tr>
    <tr>
      <td colspan="2"><strong>Vital signs Monitoring:</strong> {{ kardex.vital_signs_monitoring }}</td>           
    </tr>
    <tr>
      <td colspan="2">
        <strong>Precaution:</strong>
        <p>Fall:  {{ kardex.fall }}  Pressure ulcer: {{ kardex.pressure_ulcer }}</p>
        <p>Bleeding:  {{ kardex.bleeding }} Aspiration: {{ kardex.aspiration }}</p>
        <p>Infection: {{ kardex.infection }} Wandering:  {{ kardex.wandering }}</p>
        <p>Other: {{ kardex.other }}</p>      
      </td>     
    </tr>
    {% if resident.therapy_set.all %}
      {% for therapy in resident.therapy_set.all %}
      <tr>
        <td><strong>Therapy:</strong> {{ therapy }}</td>
        <td><strong>Schedule:</strong> {{ therapy.schedule }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td><strong>Therapy:</strong></td>
        <td><strong>Schedule:</strong></td>    
      </tr>
    {% endif %}
  </table> 
</div>
{% endwith %}

templates/kardex/includes/systematic_overview.html
<div class="social-container p-2">
  {% for diagnosis in admission.kardex.diagnosis_set.all %}
    {% ifchanged %}<strong>{{ diagnosis.system }}</strong>{% endifchanged %}
      <p><em>@{{ diagnosis.diagnosis }}</em></p>
      {% for medication in diagnosis.prescribedmedication_set.all %}
        <p>--{{ medication.medication.drug_instance }} {{ medication.medication.frequency }}</p>
      {% endfor %}
      {% for management in diagnosis.management_set.all %}
        <p>--{{ management.title }}</p>
      {% endfor %}      
  {% empty %}
        <div class="alert alert-dismissible alert-info fade show">
        <button type="button" class="close">&times;</button>
        <h4 class="alert-heading">Heads up!</h4>
        <p class="mb-0">Nothing here! <a href="{% url 'geriatrics_admin:index' %}" class="alert-link">Create</a> one now.</p>
        </div>
  {% endfor %}
  
    <div class="container">
      <div class="row">
        {% for labs in admission.laboratory_set.all %}         
        <div class="col-md-6 table-responsive-sm">
          <table class="table table-bordered table-striped">
            <tr>
              <th>Tests</th>
              <th>{{ labs.date }}</th>
            </tr>
            {% for test in labs.test_set.all %}
              <tr>
                <td>{{ test.name }}</td>
                <td>{{ test.result }}</td>
              </tr>
            {% endfor %}
          </table>
        </div>         
        {% endfor %}
      </div>
    </div>      
</div>

    
  

templates/kardex/kardex_tablist.html
<h4 class="text-center">Kardex</h4>
<!-- Tabs navs -->
<ul class="nav nav-tabs mb-3" id="tl-kardex" role="tablist">
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="kardex-tab-1"
      data-mdb-toggle="tab"
      href="#kardex-tabs-1"
      role="tab"
      aria-controls="kardex-tabs-1"
      aria-selected="false"
      >Kardex</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="kardex-tab-2"
      data-mdb-toggle="tab"
      href="#kardex-tabs-2"
      role="tab"
      aria-controls="kardex-tabs-2"
      aria-selected="false"
      >Medications</a
    >
  </li>
</ul>
<!-- Tabs navs -->

<!-- Tabs content -->
<div class="tab-content" id="kardex-content">
  <div
    class="tab-pane fade"
    id="kardex-tabs-1"
    role="tabpanel"
    aria-labelledby="kardex-tab-1"
  >
    {% include 'kardex/includes/kardex.html' %}
  </div>
  <div class="tab-pane fade" id="kardex-tabs-2" role="tabpanel" aria-labelledby="kardex-tab-2">
    {% include 'medication/medication.html' %}
  </div>
</div>
<!-- Tabs content -->

templates/kardex/systematic_overview_tablist.html
<h4 class="text-center">Systematic Overview</h4>
<!-- Tabs navs -->
<ul class="nav nav-tabs mb-3" id="tl-overview" role="tablist">
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="overview-tab-1"
      data-mdb-toggle="tab"
      href="#overview-tabs-1"
      role="tab"
      aria-controls="overview-tabs-1"
      aria-selected="false"
      >Systematic Overview</a
    >
  </li>
  <li class="nav-item" role="presentation">
    <a
      class="nav-link"
      id="overview-tab-2"
      data-mdb-toggle="tab"
      href="#overview-tabs-2"
      role="tab"
      aria-controls="overview-tabs-2"
      aria-selected="false"
      >Plan of Care</a
    >
  </li>
</ul>
<!-- Tabs navs -->

<!-- Tabs content -->
<div class="tab-content" id="overview-content">
  <div
    class="tab-pane fade"
    id="overview-tabs-1"
    role="tabpanel"
    aria-labelledby="overview-tab-1"
  >
    {% include 'kardex/includes/systematic_overview.html' %}
  </div>
  <div class="tab-pane fade" id="overview-tabs-2" role="tabpanel" aria-labelledby="overview-tab-2">
    {% include 'plan_of_care/plan_of_care.html' %}
  </div>
</div>
<!-- Tabs content -->